# Generated by Django 4.2.3 on 2023-07-20 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('done_date', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
